# Generated by Django 6.0.4 on 2026-05-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('fast-food', '快餐汉堡'), ('chinese-food', '中餐美食'), ('light-food', '轻食沙拉'), ('dessert', '甜品蛋糕'), ('snack', '小吃零食'), ('milk-tea', '奶茶饮品')], default='fast-food', max_length=20, verbose_name='分类'),
        ),
    ]
