# Generated by Django 6.0.4 on 2026-05-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='level',
            field=models.CharField(blank=True, choices=[('highly-recommend', '强烈推荐'), ('recommend', '推荐'), ('normal', '一般')], max_length=20, verbose_name='推荐等级'),
        ),
        migrations.AddField(
            model_name='post',
            name='shop_address',
            field=models.CharField(blank=True, max_length=300, verbose_name='店铺位置'),
        ),
        migrations.AddField(
            model_name='post',
            name='shop_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='店铺名称'),
        ),
    ]
