# Generated by Django 6.0.4 on 2026-04-21 14:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=20, verbose_name='口味偏好')),
                ('cuisine', models.CharField(max_length=20, verbose_name='菜系偏好')),
                ('budget', models.CharField(max_length=20, verbose_name='预算范围')),
                ('allergy', models.CharField(blank=True, default='', max_length=200, verbose_name='饮食禁忌')),
                ('demand', models.TextField(blank=True, default='', verbose_name='其他需求')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户偏好',
                'verbose_name_plural': '用户偏好列表',
                'ordering': ['-updated_at'],
            },
        ),
    ]
