# Generated by Django 6.0.4 on 2026-04-20 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('avoid', '避雷'), ('recommend', '推荐')], help_text='避雷或推荐', max_length=20, verbose_name='帖子类型')),
                ('shop_name', models.CharField(help_text='店铺或餐厅的名称', max_length=200, verbose_name='店铺名称')),
                ('shop_address', models.CharField(blank=True, help_text='店铺所在位置（选填）', max_length=300, verbose_name='店铺位置')),
                ('level', models.CharField(choices=[('super_bad', '超级踩雷'), ('bad', '难吃'), ('not_recommended', '一般不推荐'), ('expensive', '价格太贵'), ('hygiene', '卫生差')], help_text='仅避雷帖使用', max_length=20, verbose_name='避雷等级')),
                ('content', models.TextField(help_text='避雷原因或推荐理由', verbose_name='详细内容')),
                ('images', models.JSONField(blank=True, default=list, help_text='存储图片URL的JSON数组', verbose_name='图片列表')),
                ('views', models.IntegerField(default=0, help_text='帖子被查看的次数', verbose_name='浏览量')),
                ('likes', models.IntegerField(default=0, help_text='帖子获得的点赞数', verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='帖子发布时间', verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='帖子最后修改时间', verbose_name='更新时间')),
                ('author', models.ForeignKey(help_text='发布帖子的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '帖子',
                'verbose_name_plural': '帖子管理',
                'db_table': 'community_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='评论的具体内容', verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='评论发布的时间', verbose_name='评论时间')),
                ('author', models.ForeignKey(help_text='发表评论的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
                ('post', models.ForeignKey(help_text='该评论所属的帖子', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.post', verbose_name='关联帖子')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论管理',
                'db_table': 'community_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_at', models.DateTimeField(auto_now_add=True, help_text='用户点赞的时间', verbose_name='点赞时间')),
                ('post', models.ForeignKey(help_text='被点赞的帖子', on_delete=django.db.models.deletion.CASCADE, to='community.post', verbose_name='帖子')),
                ('user', models.ForeignKey(help_text='点赞的用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户点赞记录',
                'verbose_name_plural': '用户点赞记录管理',
                'db_table': 'community_user_like',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
